export const IMG_REKOGNITION_QUEUE_NAME = 'IMG_REKOGNITION_QUEUE_NAME';

export const IMG_REKOGNITION_JOB_NAME = 'IMG_REKOGNITION_JOB_NAME';

export const IMG_REKOGNITION_ERROR_LABEL = 'DETECT_ERROR';
